### ISSUE TITLE
Does this still work ?

### ISSUE THREAD

**Issue by malosaa** [kmlucy/docker-assistant-relay#4]
I did install it and follow all instructions on google.

When uploading the jsonfile, and pressing next it opens a blank window and i don't get the auth code.

My dev account is working as i have integrated already homeassistant with google, but that uses the Service Accounts, but i did make a OAuth 2.0 Client ID

any idea why ?

regards

**Comment by kmlucy** [comment]
This is based on a version of Assistant Relay that is several versions out of date and not maintained. I've kept the repository active for myself and any other active users, but I would strongly recommend starting with the current version if you are starting out. I believe the instruction link is now out of date, and I don't know the process for setting up this version.

**Comment by malosaa** [comment]
@kmlucy  

I did try to install yours, as i did the first step it doesnt give me a ip or port when starting.
it says you can now connect to http://yourip:port  like this.

Any idea?


I found a maintained version on docker from version 3.
I managed to get it working, but after 7 days it doesnt speak anymore...
When  creating new credentials with oath2 it says "there are currently no connected speakers to your home network"

Regards

**Comment by kmlucy** [comment]
I only wrote the Dockerfile, not Assistant Relay, so I'm afraid I can't really help.

**Comment by malosaa** [comment]
thanks for reply, after hours and hours of setting up and checking for a working dockercode for me, i just got it working.

v4.0b4 works i got it working trough docker.
v3 aswell now, finally

**Comment by kmlucy** [comment]
Glad to hear it!
